=== MelvynHerzig/2022-herzig/dev/tucuxi-tuberxpert/xml/response/tuberxpert_computing_response.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- ##################################################################### -->
<!-- XML Schema Definition -->
<!-- ##################################################################### -->

<xs:element name="tuberxpertResult">
<xs:complexType>
		<xs:sequence>

			<xs:element name="computationTime" type="xs:dateTime" />
			
			<xs:element name="drug" type="drugIntroType"/>

            <xs:element name="admin" type="adminType" minOccurs="0" />

            <xs:element name="covariates">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="covariate" type="covariateType" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>

            <xs:element name="treatment" type="treatmentType" minOccurs="0"/>

            <xs:element name="samples">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="sample" type="sampleType" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
		    </xs:element>

            <xs:element name="dataAdjustment" type="dataAdjustmentType"/>

            <xs:element name="parameters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="typical">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="parameter" type="parameterType" maxOccurs="unbounded" />
                                </xs:sequence>
                            </xs:complexType>
		                </xs:element>
                        <xs:element name="apriori">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="parameter" type="parameterType" maxOccurs="unbounded" />
                                </xs:sequence>
                            </xs:complexType>
		                </xs:element>
                        <xs:element name="aposteriori" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="parameter" type="parameterType" maxOccurs="unbounded" />
                                </xs:sequence>
                            </xs:complexType>
		                </xs:element>
                    </xs:sequence>
                </xs:complexType>
		    </xs:element>

            <xs:element name="statistics" type="statisticsType"/>

            <xs:element name="computationCovariates">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="computationCovariate" type="computationCovariateType" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
		    </xs:element>

		</xs:sequence>
	</xs:complexType>
</xs:element>


<!-- ##################################################################### -->
<!-- Drug info in intro -->
<!-- ##################################################################### -->

<xs:complexType name="drugIntroType">
	<xs:sequence>
		<xs:element name="drugId" type="xs:string" />
        <xs:element name="lastDose">
			<xs:complexType>
		        <xs:sequence>
		            <xs:element name="value" type="xs:decimal" minOccurs="0"/>
		            <xs:element name="unit" type="unitType" minOccurs="0"/>
		        </xs:sequence>
			</xs:complexType>
		</xs:element>
        <xs:element name="drugModelId" type="xs:string"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="adminType">
	<xs:sequence>
		<xs:element name="mandator" minOccurs="0">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="person" type="personType"/>
					<xs:element name="institute" type="instituteType" minOccurs="0" />
				</xs:sequence>
			</xs:complexType>	
		</xs:element>
		<xs:element name="patient" minOccurs="0">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="person" type="personType"/>
					<xs:element name="institute" type="instituteType" minOccurs="0" />
				</xs:sequence>
			</xs:complexType>	
		</xs:element>
		<xs:element name="clinicalData" minOccurs="0">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="clinicalDataEntry" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:simpleContent>
								<xs:extension base="xs:string">
									<xs:attribute name="key" use="required" type="xs:string"/>
								</xs:extension>
							</xs:simpleContent>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="personType">
	<xs:sequence>
		<xs:element name="id" type="xs:string" minOccurs="0" />
		<xs:element name="title" type="xs:string" minOccurs="0" />
		<xs:element name="firstName" type="xs:string" />
		<xs:element name="lastName" type="xs:string" />
		<xs:group ref="contactGroup" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="instituteType">
	<xs:sequence>
		<xs:element name="id" type="xs:string" minOccurs="0" />
		<xs:element name="name" type="xs:string" />
		<xs:group ref="contactGroup" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="addressType">
	<xs:sequence>
		<xs:element name="street" type="xs:string" />
		<xs:element name="postCode" >
			<xs:simpleType>
				 <xs:restriction base="xs:string">
				 	<!-- 4 digit number that can't begin with a 0 -->
			     	<xs:pattern value="[1-9]([0-9]{3})" />
			    </xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="city" type="xs:string" />
		<xs:element name="state" type="xs:string" minOccurs="0" />
		<xs:element name="country" type="xs:string" minOccurs="0" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="phoneType">
	<xs:sequence>
		<!-- Number hasn't a regex restriction because of other coutries phone numbers -->
		<xs:element name="number" type="xs:string" />
		<xs:element name="type" type="coordinateType" minOccurs="0" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="emailType">
	<xs:sequence>
		<xs:element name="address">
			<xs:simpleType>
    			<xs:restriction base="xs:string">
        			<xs:pattern value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"/>
    			</xs:restriction>
			</xs:simpleType>
		</xs:element>	
		<xs:element name="type" type="coordinateType" minOccurs="0" />
	</xs:sequence>
</xs:complexType>

<xs:simpleType name="coordinateType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="private" />
		<xs:enumeration value="professional" />
	</xs:restriction>
</xs:simpleType>

<xs:group name="contactGroup">
	<xs:sequence>
		<xs:element name="address" type="addressType" minOccurs="0" />
		<xs:element name="phone" type="phoneType" minOccurs="0" />
		<xs:element name="email" type="emailType" minOccurs="0" />
	</xs:sequence>
</xs:group>

<!-- ##################################################################### -->
<!-- Covariates -->
<!-- ##################################################################### -->

<xs:complexType name="covariateType">
	<xs:sequence>
		<xs:element name="covariateId" type="xs:string" />
		<xs:element name="date" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="name" type="xs:string" />
		<xs:element name="value" type="xs:string" />
		<xs:element name="unit" type="unitType" />
		<xs:element name="desc" type="xs:string" />
        <xs:element name="source"  minOccurs="0">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="patient" />
					<xs:enumeration value="default" />
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
        <xs:element name="warning" type="warningType" minOccurs="0" />
	</xs:sequence>
</xs:complexType>

<!-- ##################################################################### -->
<!-- Treatment -->
<!-- ##################################################################### -->

<xs:complexType name="treatmentType">
	<xs:sequence>
		<xs:element name="dosageHistory" type="dosageHistoryType" minOccurs="0" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="dosageHistoryType">
	<xs:sequence>
		<xs:element name="dosageTimeRange" type="dosageTimeRangeType" minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="dosageTimeRangeType">
	<xs:sequence>
		<xs:group ref="dateIntervalGroup" />
		<xs:element name="dosage" type="dosageType" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="dosageType">
	<xs:choice>
		<xs:element name="dosageLoop" type="dosageLoopType" />
		<xs:element name="dosageSteadyState" type="dosageSteadyStateType" />
		<xs:group ref="dosageBoundedGroup" />
	</xs:choice>
</xs:complexType>

<xs:complexType name="dosageLoopType">
  <xs:sequence>
    <xs:group ref="dosageBoundedGroup" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="dosageSteadyStateType">
  <xs:sequence>
    <xs:element name="lastDoseDate" type="xs:dateTime" />
    <xs:group ref="dosageBoundedGroup" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="dosageRepeatType">
	<xs:sequence>
		<xs:element name="iterations">
			<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="1" />
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:group ref="dosageBoundedGroup" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="dosageSequenceType">
	<xs:sequence>
		<xs:group ref="dosageBoundedGroup" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="lastingDosageType">
	<xs:sequence>
		<xs:element name="interval" type="xs:time" />
		<xs:group ref="intakeGroup" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="dailyDosageType">
	<xs:sequence>
		<xs:element name="time" type="xs:time" />
		<xs:group ref="intakeGroup" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="weeklyDosageType">
	<xs:sequence>
		<xs:element name="day">
		 	<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="0" />
					<xs:maxInclusive value="6" />
				</xs:restriction>
			</xs:simpleType>
    	</xs:element>
		<xs:element name="time" type="xs:time" />
		<xs:group ref="intakeGroup" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="doseType">
	<xs:sequence>
		<xs:element name="value" type="xs:decimal" />
		<xs:element name="unit" type="unitType" />
		<xs:element name="infusionTimeInMinutes" type="xs:decimal" minOccurs="0"/>
        <xs:element name="warning" type="warningType" minOccurs="0" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="formulationAndRouteType">
	<xs:sequence>
		<xs:element name="formulation">
			<xs:simpleType>
				<!-- This enumeration is based on the one present in formulationandroute.h file in Tucuxi -->
				<xs:restriction base="xs:string">
		            <xs:enumeration value="undefined" />
		            <xs:enumeration value="parenteralSolution" />
		            <xs:enumeration value="oralSolution" />
		            <xs:enumeration value="test" />
		        </xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="administrationName" type="xs:string" />
		<xs:element name="administrationRoute">
			<xs:simpleType>
				<!-- This enumeration is based on the one present in formulationandroute.h file in Tucuxi -->
				<xs:restriction base="xs:string">
		            <xs:enumeration value="undefined" />
		            <xs:enumeration value="intramuscular" />
		            <xs:enumeration value="intravenousBolus" />
		            <xs:enumeration value="intravenousDrip" />
		            <xs:enumeration value="nasal" />
		            <xs:enumeration value="oral" />
		            <xs:enumeration value="rectal" />
		            <xs:enumeration value="subcutaneous" />
		            <xs:enumeration value="sublingual" />
		            <xs:enumeration value="transdermal" />
		            <xs:enumeration value="vaginal" />
		        </xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="absorptionModel">
			<xs:simpleType>
				<!-- This enumeration is based on the one present in definitions.h file in Tucuxi -->
				<xs:restriction base="xs:string">
		            <xs:enumeration value="undefined" />
		            <xs:enumeration value="intravascular" />
		            <xs:enumeration value="extravascular" />
		            <xs:enumeration value="extravascularLag" />
		            <xs:enumeration value="infusion" />
		        </xs:restriction>
			</xs:simpleType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<!-- ##################################################################### -->
<!-- Samples -->
<!-- ##################################################################### -->

<xs:complexType name="sampleType">
	<xs:sequence>
		<xs:element name="sampleId" type="xs:positiveInteger"/>
		<xs:element name="sampleDate" type="xs:dateTime" />
		<xs:element name="concentrations">
	      	<xs:complexType>
		        <xs:sequence>
		          	<xs:element name="concentration" maxOccurs="unbounded">
				      	<xs:complexType>
				        	<xs:sequence>
				          		<xs:element name="analyteId" type="xs:string" />
                                <xs:element name="percentile" type="xs:decimal" />
					          	<xs:element name="value" type="xs:decimal" />
					          	<xs:element name="unit" type="unitType" />
                                <xs:element name="warning" type="warningType" minOccurs="0"/>
				        	</xs:sequence>
				      	</xs:complexType>
					</xs:element>
		        </xs:sequence>
	      	</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<!-- ##################################################################### -->
<!-- Data adjustment -->
<!-- ##################################################################### -->

<xs:complexType name="dataAdjustmentType">
	<xs:sequence>
        <xs:element name="analyteIds">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="analyteId" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
		</xs:element>
		<xs:element name="adjustments">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="adjustment" type="adjustmentType" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
            </xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="adjustmentType">
	<xs:sequence>
		<xs:element name="score" type="xs:decimal" />
		<xs:element name="targetEvaluations">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="targetEvaluation" type="targetEvaluationType" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
		</xs:element>
        <xs:element name="dosageHistory" type="dosageHistoryType"/>
        <xs:element name="cycleDatas">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="cycleData" type="cycleDataType" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="targetEvaluationType">
	<xs:sequence>
		<xs:element name="targetType">
			<xs:simpleType>
				<!-- This enumeration is based on the one present in the drug file's XSD -->
				<xs:restriction base="xs:string">
		            <xs:enumeration value="peak" />
		            <xs:enumeration value="residual" />
		            <xs:enumeration value="mean" />
		            <xs:enumeration value="auc" />
		            <xs:enumeration value="aucOverMic" /> <!-- In that case MIC should be a covariate -->
		            <xs:enumeration value="timeOverMic" /> <!-- In that case MIC should be a covariate -->
		            <xs:enumeration value="aucDividedByMic" /> <!-- In that case MIC should be a covariate -->
		            <xs:enumeration value="peakDividedByMic" /> <!-- In that case MIC should be a covariate -->
		        </xs:restriction>
			</xs:simpleType>
		</xs:element>
        <xs:element name="unit" type="unitType" />
        <xs:element name="value" type="xs:decimal" />
        <xs:element name="score" type="xs:decimal" />
        <xs:element name="min" type="xs:decimal" />
        <xs:element name="best" type="xs:decimal" />
        <xs:element name="max" type="xs:decimal" />
        <xs:element name="inefficacyAlarm" type="xs:decimal" />
        <xs:element name="toxicityAlarm" type="xs:decimal" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="cycleDataType">
	<xs:sequence>
        <xs:element name="start" type="xs:dateTime" />
		<xs:element name="end" type="xs:dateTime" />
        <xs:element name="unit" type="unitType" />
        <xs:element name="times" type="xs:string" />
        <xs:element name="values" type="xs:string" />
	</xs:sequence>
</xs:complexType>

<!-- ##################################################################### -->
<!-- Parameter -->
<!-- ##################################################################### -->

<xs:complexType name="parameterType">
	<xs:sequence>
        <xs:element name="id" type="xs:string" />
        <xs:element name="value" type="xs:decimal" />
	</xs:sequence>
</xs:complexType>

<!-- ##################################################################### -->
<!-- Statistics -->
<!-- ##################################################################### -->

<xs:complexType name="statisticsType">
	<xs:sequence>
        <xs:element name="auc24" type="xs:decimal" />
        <xs:element name="peak" type="xs:decimal" />
        <xs:element name="residual" type="xs:decimal" />
	</xs:sequence>
</xs:complexType>

<!-- ##################################################################### -->
<!-- Computation covariates -->
<!-- ##################################################################### -->

<xs:complexType name="computationCovariateType">
	<xs:sequence>
        <xs:element name="id" type="xs:string" />
        <xs:element name="value" type="xs:decimal" />
	</xs:sequence>
</xs:complexType>

<!-- ##################################################################### -->
<!-- Misc -->
<!-- ##################################################################### -->

<xs:complexType name="warningType">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="level" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="normal" />
                        <xs:enumeration value="critical" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:group name="dateIntervalGroup">
	<xs:sequence>
		<xs:element name="start" type="xs:dateTime" />
		<xs:element name="end" type="xs:dateTime" />
	</xs:sequence>
</xs:group>

<xs:group name="dosageBoundedGroup">
	<xs:choice>
		<xs:element name="dosageRepeat" type="dosageRepeatType" />
		<xs:element name="dosageSequence" type="dosageSequenceType" />
		<xs:choice>
			<xs:element name="lastingDosage" type="lastingDosageType" />
			<xs:element name="dailyDosage" type="dailyDosageType" />
			<xs:element name="weeklyDosage" type="weeklyDosageType" />
		</xs:choice>
	</xs:choice>
</xs:group>

<xs:group name="intakeGroup">
	<xs:sequence>
		<xs:element name="dose" type="doseType" />
		<xs:element name="formulationAndRoute" type="formulationAndRouteType" />
	</xs:sequence>
</xs:group>

<xs:simpleType name="unitType">
    <xs:restriction base="xs:normalizedString">
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== MelvynHerzig/2022-herzig/publi/example_reports/e3_rifampicin_1_11-7-2018_13h45m30s.xml
<tuberxpertResult xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='tuberxpert_computing_response.xsd'>
	<computationTime>2018-07-11T13:45:30</computationTime>
	<language>en</language>
	<drug>
		<drugId>rifampicin</drugId>
		<lastDose/>
		<drugModelId>ch.tucuxi.rifampicin.svensson2017</drugModelId>
	</drug>
	<admin>
		<mandator>
			<person>
				<firstName>John</firstName>
				<lastName>Doe</lastName>
			</person>
			<institute>
				<name>CHUV</name>
			</institute>
		</mandator>
		<patient>
			<person>
				<firstName>Alice</firstName>
				<lastName>Aupaysdesmerveilles</lastName>
			</person>
			<institute>
				<name>EHNV</name>
			</institute>
		</patient>
		<clinicalDatas/>
	</admin>
	<covariates>
		<covariate>
			<covariateId>ffm</covariateId>
			<name>Fat-Free Mass</name>
			<value>70.000000</value>
			<unit>kg</unit>
			<dataType>double</dataType>
			<desc>The fat-free mass of the patient</desc>
			<source>default</source>
		</covariate>
	</covariates>
	<treatment>
		<dosageHistory/>
	</treatment>
	<samples/>
	<dataAdjustment>
		<analyteIds/>
		<adjustments>
			<adjustment>
				<score>0.974068</score>
				<targetEvaluations>
					<targetEvaluation>
						<targetType>residual</targetType>
						<unit>ug/l</unit>
						<value>1057.397106</value>
						<score>0.974068</score>
						<min>750.000000</min>
						<best>1000.000000</best>
						<max>1500.000000</max>
						<inefficacyAlarm>0.000000</inefficacyAlarm>
						<toxicityAlarm>10000.000000</toxicityAlarm>
					</targetEvaluation>
				</targetEvaluations>
				<dosageHistory>
					<dosageTimeRange>
						<start>2018-07-11T14:45:30</start>
						<end>2018-07-12T02:45:30</end>
						<dosage>
							<dosageRepeat>
								<iterations>1</iterations>
								<lastingDosage>
									<interval>12:00:00</interval>
									<dose>
										<value>1400.000000</value>
										<unit>mg</unit>
										<infusionTimeInMinutes>0.000000</infusionTimeInMinutes>
									</dose>
									<formulationAndRoute>
										<formulation>parenteralSolution</formulation>
										<administrationName>admname</administrationName>
										<administrationRoute>oral</administrationRoute>
										<absorptionModel>extravascular</absorptionModel>
									</formulationAndRoute>
								</lastingDosage>
							</dosageRepeat>
						</dosage>
					</dosageTimeRange>
					<dosageTimeRange>
						<start>2018-07-12T02:45:30</start>
						<end>2018-07-18T14:45:30</end>
						<dosage>
							<dosageRepeat>
								<iterations>14</iterations>
								<lastingDosage>
									<interval>12:00:00</interval>
									<dose>
										<value>1300.000000</value>
										<unit>mg</unit>
										<infusionTimeInMinutes>0.000000</infusionTimeInMinutes>
									</dose>
									<formulationAndRoute>
										<formulation>parenteralSolution</formulation>
										<administrationName>admname</administrationName>
										<administrationRoute>oral</administrationRoute>
										<absorptionModel>extravascular</absorptionModel>
									</formulationAndRoute>
								</lastingDosage>
							</dosageRepeat>
						</dosage>
					</dosageTimeRange>
				</dosageHistory>
				<cycleDatas>
					<cycleData>
						<start>2018-07-11T14:45:30</start>
						<end>2018-07-12T02:45:30</end>
						<unit>ug/l</unit>
						<times>0.000000,0.050000,0.100000,0.150000,0.200000,0.250000,0.300000,0.350000,0.400000,0.450000,0.500000,0.550000,0.600000,0.650000,0.700000,0.750000,0.800000,0.850000,0.900000,0.950000,1.000000,1.050000,1.100000,1.150000,1.200000,1.250000,1.300000,1.350000,1.400000,1.450000,1.500000,1.550000,1.600000,1.650000,1.700000,1.750000,1.800000,1.850000,1.900000,1.950000,2.000000,2.050000,2.100000,2.150000,2.200000,2.250000,2.300000,2.350000,2.400000,2.450000,2.500000,2.550000,2.600000,2.650000,2.700000,2.750000,2.800000,2.850000,2.900000,2.950000,3.000000,3.050000,3.100000,3.150000,3.200000,3.250000,3.300000,3.350000,3.400000,3.450000,3.500000,3.550000,3.600000,3.650000,3.700000,3.750000,3.800000,3.850000,3.900000,3.950000,4.000000,4.050000,4.100000,4.150000,4.200000,4.250000,4.300000,4.350000,4.400000,4.450000,4.500000,4.550000,4.600000,4.650000,4.700000,4.750000,4.800000,4.850000,4.900000,4.950000,5.000000,5.050000,5.100000,5.150000,5.200000,5.250000,5.300000,5.350000,5.400000,5.450000,5.500000,5.550000,5.600000,5.650000,5.700000,5.750000,5.800000,5.850000,5.900000,5.950000,6.000000,6.050000,6.100000,6.150000,6.200000,6.250000,6.300000,6.350000,6.400000,6.450000,6.500000,6.550000,6.600000,6.650000,6.700000,6.750000,6.800000,6.850000,6.900000,6.950000,7.000000,7.050000,7.100000,7.150000,7.200000,7.250000,7.300000,7.350000,7.400000,7.450000,7.500000,7.550000,7.600000,7.650000,7.700000,7.750000,7.800000,7.850000,7.900000,7.950000,8.000000,8.050000,8.100000,8.150000,8.200000,8.250000,8.300000,8.350000,8.400000,8.450000,8.500000,8.550000,8.600000,8.650000,8.700000,8.750000,8.800000,8.850000,8.900000,8.950000,9.000000,9.050000,9.100000,9.150000,9.200000,9.250000,9.300000,9.350000,9.400000,9.450000,9.500000,9.550000,9.600000,9.650000,9.700000,9.750000,9.800000,9.850000,9.900000,9.950000,10.000000,10.050000,10.100000,10.150000,10.200000,10.250000,10.300000,10.350000,10.400000,10.450000,10.500000,10.550000,10.600000,10.650000,10.700000,10.750000,10.800000,10.850000,10.900000,10.950000,11.000000,11.050000,11.100000,11.150000,11.200000,11.250000,11.300000,11.350000,11.400000,11.450000,11.500000,11.550000,11.600000,11.650000,11.700000,11.750000,11.800000,11.850000,11.900000,11.950000,12.000000</times>
						<values>0.000000,0.000000,0.000000,0.000039,0.008863,0.368951,5.370676,38.420343,165.869302,494.664221,1120.246578,2065.149018,3265.973410,4612.055373,5995.185873,7338.075021,8598.049661,9757.935416,10815.200173,11774.172833,12641.723771,13425.265075,14131.962407,14768.481111,15340.937768,15854.920730,16315.529566,16727.416967,17094.828390,17421.638385,17711.383613,17967.292820,18192.314042,18389.139338,18560.227268,18707.823358,18833.978721,18940.567030,19029.299973,19101.741349,19159.319920,19203.341134,19234.997813,19255.379919,19265.483451,19266.218580,19258.417068,19242.839041,19220.179182,19191.072372,19156.098859,19115.788965,19070.627393,19021.057160,18967.483189,18910.275591,18849.772662,18786.283626,18720.091136,18651.453560,18580.607075,18507.767571,18433.132402,18356.881977,18279.181219,18200.180896,18120.018839,18038.821053,17956.702734,17873.769200,17790.116738,17705.833378,17620.999608,17535.689017,17449.968891,17363.900750,17277.540848,17190.940623,17104.147110,17017.203318,16930.148578,16843.018859,16755.847051,16668.663237,16581.494925,16494.367278,16407.303305,16320.324055,16233.448777,16146.695081,16060.079072,15973.615482,15887.317787,15801.198315,15715.268343,15629.538185,15544.017279,15458.714255,15373.637011,15288.792770,15204.188138,15119.829159,15035.721361,14951.869798,14868.279095,14784.953478,14701.896811,14619.112629,14536.604158,14454.374351,14372.425900,14290.761268,14209.382700,14128.292245,14047.491772,13966.982985,13886.767433,13806.846527,13727.221551,13647.893670,13568.863938,13490.133312,13411.702656,13333.572750,13255.744294,13178.217918,13100.994184,13024.073593,12947.456589,12871.143564,12795.134859,12719.430773,12644.031559,12568.937435,12494.148578,12419.665136,12345.487222,12271.614919,12198.048285,12124.787348,12051.832115,11979.182569,11906.838670,11834.800358,11763.067556,11691.640164,11620.518068,11549.701136,11479.189221,11408.982159,11339.079775,11269.481875,11200.188257,11131.198701,11062.512979,10994.130849,10926.052056,10858.276336,10790.803414,10723.633003,10656.764806,10590.198517,10523.933819,10457.970386,10392.307881,10326.945961,10261.884270,10197.122447,10132.660119,10068.496906,10004.632420,9941.066263,9877.798029,9814.827306,9752.153671,9689.776696,9627.695942,9565.910966,9504.421313,9443.226523,9382.326130,9321.719657,9261.406621,9201.386533,9141.658896,9082.223204,9023.078947,8964.225606,8905.662655,8847.389562,8789.405787,8731.710785,8674.304002,8617.184878,8560.352848,8503.807338,8447.547769,8391.573555,8335.884104,8280.478817,8225.357089,8170.518309,8115.961859,8061.687115,8007.693448,7953.980222,7900.546795,7847.392519,7794.516741,7741.918801,7689.598034,7637.553769,7585.785329,7534.292032,7483.073191,7432.128111,7381.456095,7331.056438,7280.928431,7231.071359,7181.484503,7132.167136,7083.118530,7034.337949,6985.824653,6937.577896,6889.596930,6841.881000,6794.429345,6747.241203,6700.315804,6653.652375,6607.250140,6561.108315,6515.226114,6469.602747,6424.237419,6379.129330,6334.277678,6289.681655,6245.340450</values>
					</cycleData>
					<cycleData>
						<start>2018-07-12T02:45:30</start>
						<end>2018-07-12T14:45:30</end>
						<unit>ug/l</unit>
